name: Android Emulator

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip lib32stdc++6 lib32z1

    - name: Download and set up Android SDK tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        sudo mkdir -p /usr/lib/android-sdk/cmdline-tools/latest
        sudo mv cmdline-tools/cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest
        echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install SDK packages
      run: |
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

    - name: Create and start emulator
      run: |
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel" --force
        echo "hw.gpu.mode=auto" >> ~/.android/avd/test.avd/config.ini
        echo "hw.gpu.enabled=yes" >> ~/.android/avd/test.avd/config.ini
        nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot-load -no-window -gpu swiftshader_indirect -qemu -m 2048 > /dev/null 2>&1 &

    - name: Wait for emulator to start
      run: |
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        adb wait-for-device

    - name: Install APK
      run: |
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        adb install your-app.apk
      env:
        APK_PATH: your-app.apk

    - name: Forward port
      run: |
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        ssh -R 0.0.0.0:5554:127.0.0.1:5554 serveo.net
